# Generated by Django 4.1.3 on 2022-11-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nome_mensagem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
