# Generated by Django 4.1.3 on 2022-11-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mensagem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='email',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
