# Generated by Django 4.1.3 on 2022-11-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mensagem_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
