# Generated by Django 4.1.3 on 2022-11-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_mensagem_mensagem_alter_mensagem_phone_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Mensagem", new_name="Mensagen",),
    ]
